### ISSUE TITLE
wiki proces

### ISSUE THREAD

**Issue by qiubee** [Loquino/functional-programming#3]
# Wiki
* Ik zie nog niet het proces van je data-opschoon-functie. Dat kan je nog kan toevoegen.
* Je hebt het concept beschreven in je wiki. Die zou je kunnen verkorten en in de readme zetten.
* Goed bezig met het noteren van het proces in de wiki :+1:. Misschien nog meer van het proces laten zien door uit te leggen hoe je de code hebt gemaakt.

**Comment by deinca** [comment]
Dankjewel kevin dit is opgelost 🗡
