### ISSUE TITLE
Vervang innerHTML om content in html te zetten

### ISSUE THREAD

**Issue by qiubee** [Loquino/functional-programming#4]
Het wordt algemeen afgeraden om `innerHTML` te gebruiken in JavaScript omdat je daarmee cross-site scripting aanvallen (XSS) mee kan uitvoeren. Het is beter om `textContent` te gebruiken. Dit maakt de applicatie veiliger.

https://github.com/Loquino/functional-programming/blob/31a5504dd75a33d938b7f08e7116003d2b5dc7f9/App/public/js/functions.js#L44-L50

**Comment by deinca** [comment]
Thanks Kevin dit heb ik opgepakt en heb het veranderd naar textContent :)
