### ISSUE TITLE
Feedback documentatie

### ISSUE THREAD

**Issue by roberrrt-s** [Loquino/functional-programming#5]
Hi Deiver.

Nette manier van documenteren, het gebruik van Projects als management tool is een slimme zet. Ik vind je logboek wel minimaal, dus daar zou je evt. een slag kunnen maken als je er nog tijd voor hebt. Probeer bijvoorbeeld wat meer details te geven over wat voor code je op welke dag hebt geschreven, het is handig om dit direct end of day te doen zodat je dit later kan aanvullen met tekst waarom je bepaalde keuzes hebt gemaakt. Werk je verder nog even de opstaande issues af? Dan wens ik je verder veel succes vandaag!

**Comment by deinca** [comment]
Hey Robert, Dank je wel voor je feedback ik zal ernaar kijken en zoveel mogelijk documenteren.
